name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT_KEY }}

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-nodejs-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-nodejs-app
